@startuml

skinparam linetype ortho

class ListUI {}

interface Image {
  + draw(): void
}

class ProxyImage implements Image {
  - real: RealImage
}

class RealImage implements Image {}

ListUI .> Image
ProxyImage -> RealImage

@enduml
