/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FlowControllerTest {
    @Test void testProcess() {
        ByteSource mockSource = new MockByteSource();
        FlowController fc = new FlowController(mockSource);
        fc.process(); 
    }
}
