/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package study;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ArrayList<Item> items = new ArrayList<>();
        Item item = new Item(1000);
        items.add(item);
        DiscountStrategy discountStrategy = new FirstGuestDiscountStrategy();
        Calculator calculator = new Calculator(discountStrategy);
        int price = calculator.calculate(items);
        System.out.println(price);
    }
}
