/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import oop.section09.ApplicationMediator;
import oop.section09.DesktopColleague;
import oop.section09.MobileColleague;
import oop.section09.NintendoSwitchColleague;

public class App {
    public static void main(String[] args) {

        ApplicationMediator mediator = new ApplicationMediator();
        var desktop = new DesktopColleague(mediator);
        var mobile = new MobileColleague(mediator);
        var nintendoSwitch = new NintendoSwitchColleague(mediator);
        mediator.addColleague(desktop);
        mediator.addColleague(mobile);
        mediator.addColleague(nintendoSwitch);
        desktop.send("desktop says, Hello World");
        mobile.send("mobile says, Hello");
    }
}
